-----------------------------------------------------------------------------------------------------
-- Business Problems - Advanced Analysis
-----------------------------------------------------------------------------------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

-- Join orders, order_items, products tables
-- find the total sales
-- group by product id
-- top 10 products

ALTER TABLE order_items
ADD COLUMN total_sales FLOAT;

-- update quantity * units
SELECT * FROM category;

UPDATE order_items
SET total_sales = quantity * price_per_unit;
SELECT * FROM order_items
WHERE quantity > 1;

SELECT 
	p.product_id,
	p.product_name,
	ROUND(CAST(SUM(total_sales) AS numeric),2) AS total_sales,
	COUNT(o.order_id) AS total_orders
FROM orders AS o
INNER JOIN order_items AS oi
ON o.order_id = oi.order_id
INNER JOIN products AS p
ON oi.product_id = p.product_id
GROUP BY 1,2
ORDER BY total_sales DESC
LIMIT 10;

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

-- category_id , category_name, total_sales


SELECT 
	p.category_id,
	c.category_name,
	ROUND(CAST(SUM(oi.total_sales) AS numeric),2) AS total_sale,
	ROUND(CAST(SUM(oi.total_sales)/(SELECT SUM(total_sales) FROM order_items)*100 AS numeric),2) AS perc_contribution
FROM order_items AS oi
INNER JOIN products AS p
ON oi.product_id = p.product_id
INNER JOIN category AS c
ON p.category_id = c.category_id
GROUP BY 1,2
ORDER BY 3 DESC

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

-- orders join to order_items joined to customers table

SELECT * FROM orders

SELECT 
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	ROUND(CAST(SUM(oi.total_sales)/COUNT(o.order_id) AS numeric),2) AS average_order_value,
	COUNT(o.order_id) AS total_orders
FROM orders AS o
LEFT JOIN order_items AS oi
ON o.order_id = oi.order_id
LEFT JOIN customers AS c
ON c.customer_id = o.customer_id
GROUP BY 1,2
HAVING COUNT(o.order_id) > 5
ORDER BY 4 DESC

/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/

-- last 1 year of data
-- each month, their sale and prev month sale
-- window lag
SELECT
	year,
	month,
	total_sales AS current_month_sale,
	LAG(total_sales, 1) OVER(ORDER BY year, month) AS last_month_sale
FROM
(
SELECT 
	EXTRACT(MONTH from order_date) AS month,
	EXTRACT(YEAR from order_date) AS year,
	ROUND(SUM(oi.total_sales::numeric),2) AS total_sales
FROM orders  as o
INNER JOIN order_items AS oi
USING(order_id)
WHERE order_date >= CURRENT_DATE - INTERVAL '2 year'
GROUP BY 1,2
ORDER BY 2,1) AS t1

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/

SELECT 
	 DISTINCT c.customer_id ,
	 c.first_name,
	 c.last_name
FROM customers AS c
LEFT JOIN orders AS o
ON o.customer_id=c.customer_id
WHERE o.order_id IS NULL

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/
SELECT 
	category,
	state,
	total_sales
FROM( 
SELECT 
	ct.category_name AS category,
	cust.state AS state,
	SUM(oit.total_sales) AS total_sales,
	RANK() OVER(PARTITION BY cust.state ORDER BY SUM(oit.total_sales) ASC) AS rank
FROM category AS ct
JOIN products as pt
ON pt.category_id=ct.category_id
JOIN order_items as oit
ON oit.product_id=pt.product_id
JOIN orders as ot
ON ot.order_id=oit.order_id
JOIN customers as cust
ON cust.customer_id=ot.customer_id
GROUP BY 1,2) AS T1
WHERE rank = 1
GROUP BY 1,2,3;

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

SELECT 
	ot.customer_id,
	ROUND(SUM(oit.total_sales)::numeric,2) AS CLTV,
	DENSE_RANK() OVER(ORDER BY SUM(oit.total_sales) DESC) AS rank
FROM order_items AS oit
JOIN orders AS ot
ON ot.order_id=oit.order_id
GROUP BY 1

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT * FROM inventory
WHERE stock<10

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

SELECT 
  ct.first_name,
  ot.*,
  (st.shipping_date - ot.order_date) AS delivery_time
FROM shipping AS st
JOIN orders AS ot
  ON ot.order_id = st.order_id
JOIN customers AS ct
  ON ct.customer_id = ot.customer_id
WHERE (st.shipping_date - ot.order_date) > 3;

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT 
	payment_status,
	COUNT(*) AS total_count,
	COUNT(*)::numeric/(SELECT COUNT(*) FROM orders)::numeric *100 AS total_orders
FROM payments AS p
JOIN orders AS o
ON p.order_id = o.order_id
GROUP BY 1

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/

SELECT 
  T1.*,
  successful_orders::numeric 
  / (successful_orders + fail_orders) * 100 AS percentage_of_success
FROM (
  SELECT 
    st.seller_id,
    st.seller_name,
    SUM(oit.total_sales) AS total_sales,
    COUNT(CASE WHEN order_status = 'Completed' THEN 1 END) AS successful_orders,
    COUNT(CASE WHEN order_status = 'Returned' THEN 1 END) AS fail_orders
  FROM orders AS ot
  JOIN order_items AS oit
    ON oit.order_id = ot.order_id
  JOIN sellers AS st 
    ON st.seller_id = ot.seller_id
  GROUP BY st.seller_id, st.seller_name
  ORDER BY total_sales DESC
  LIMIT 5
) AS T1;

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT 
	*,
	price-cogs AS profit 
FROM products
ORDER BY  profit DESC;

/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

SELECT
  product_id,
  COUNT(CASE WHEN order_status = 'Returned' THEN 1 END) AS total_returns,
  SUM(CASE WHEN order_status = 'Returned' THEN 1 ELSE 0 END)::numeric
    / COUNT(*) * 100 AS percentage
FROM orders AS ot
JOIN order_items AS oit
  ON oit.order_id = ot.order_id
GROUP BY product_id
ORDER BY total_returns DESC
LIMIT 10;

/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

SELECT * FROM orders AS ot
JOIN payments AS pt
ON pt.order_id=ot.order_id
JOIN customers as ct
ON ct.customer_id=ot.customer_id
WHERE order_status='Inprogress' AND payment_status='Payment Successed'

/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

SELECT 
  ot.seller_id,
  MAX(ot.order_date) AS last_sale_date,
  SUM(oit.total_sales) AS total_sales
FROM orders AS ot
JOIN order_items AS oit
ON ot.order_id=oit.order_id
WHERE ot.order_status = 'Completed'
GROUP BY ot.seller_id
HAVING MAX(ot.order_date) < CURRENT_DATE - INTERVAL '6 months';


/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/
SELECT 
	*,
	CASE 
		WHEN total_return > 5 THEN 'returning' ELSE 'new'
		END
FROM(
SELECT 
	DISTINCT ct.customer_id,
	ct.first_name AS name,
	COUNT(*) AS total_orders,
	count(CASE WHEN ot.order_status ='Returned' THEN 1 END ) AS total_return
FROM orders AS ot
LEFT JOIN customers as ct
ON ct.customer_id=ot.customer_id
GROUP BY 1
) AS t1

/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/
SELECT * FROM (
SELECT 
	ct.customer_id,
	ct.state,
	COUNT(oit.order_id) AS no_of_orders,
	SUM(oit.total_sales) AS total_sales,
	DENSE_RANK() OVER(PARTITION BY ct.state ORDER BY COUNT(oit.order_id)DESC) AS rank
FROM customers AS ct
JOIN orders AS ot
ON ot.customer_id= ct.customer_id
JOIN order_items AS oit 
ON oit.order_id=ot.order_id
GROUP BY 1,2
) AS t1
WHERE RANK <6

/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

SELECT 
	st.shipping_providers,
	COUNT(st.order_id),
	SUM(oit.total_sales) AS total_revenue,
	AVG(st.shipping_date - ot.order_date) AS avg_delivery_time
FROM shipping AS st
JOIN orders AS ot 
ON ot.order_id=st.order_id
JOIN order_items AS oit
ON oit.order_id=ot.order_id
GROUP BY 1


/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio 
at end Round the result
Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/

SELECT 
    product_id,
    product_name,
    category_name,
    ROUND(SUM(CASE WHEN year = 2022 THEN total_sales END)::numeric, 2) AS revenue_2022,
    ROUND(SUM(CASE WHEN year = 2023 THEN total_sales END)::numeric, 2) AS revenue_2023,
    ROUND(
        (
            (SUM(CASE WHEN year = 2023 THEN total_sales END) 
           - SUM(CASE WHEN year = 2022 THEN total_sales END)) 
           / NULLIF(SUM(CASE WHEN year = 2022 THEN total_sales END), 0) * 100
        )::numeric 
    , 2) AS decrease_ratio
FROM (
    SELECT 
        oit.product_id,
        pt.product_name,
        ct.category_name,
        oit.total_sales,
        EXTRACT(YEAR FROM ot.order_date) AS year
    FROM orders AS ot
    JOIN order_items AS oit
        ON oit.order_id = ot.order_id
    JOIN products AS pt
        ON pt.product_id = oit.product_id
    JOIN category AS ct
        ON ct.category_id = pt.category_id
) AS t1
GROUP BY 1,2,3
HAVING 
    SUM(CASE WHEN year = 2023 THEN total_sales END)
  < SUM(CASE WHEN year = 2022 THEN total_sales END)
ORDER BY decrease_ratio ASC
LIMIT 10;
